Better verification messaging
Sage-Bionetworks/BridgeServer2 pull request #105
Opened 2019-09-05 20:18 UTC by alxdarksage

We now keep the token around so we can reidentify the account and return a more helpful message when we can conclude the token was already used to verify the email address/phone number.

2019-09-05 22:16 UTC, DwayneJengSage requested changes
Overall looks good. One question about unit tests and the VerificationData.

2019-09-05 22:16 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/AccountWorkflowService.java
> +        saveVerification(sptoken, new VerificationData(study.getIdentifier(), ChannelType.EMAIL, userId, expiresOn));
Do we have any unit tests that verify that we're saving the expiresOn to the cacheProvider correctly? (For both email and phone case.)

2019-09-05 23:52 UTC, DwayneJengSage requested changes
I think there was a misunderstanding. I was asking for a test that verifies that we set expiresOn correctly when creating VerificationData.

2019-09-06 17:26 UTC, alxdarksage commented
Updated based on your latest comment (checking the timestamp that's being persisted in VerificationData).

2019-09-06 18:03 UTC, DwayneJengSage approved these changes

2019-09-09 17:05 UTC, merged