Assessment ownership now expressed by association to an organization.
Sage-Bionetworks/BridgeServer2 pull request #229
Opened 2020-06-29 22:34 UTC by alxdarksage

Edits to assessments can either be done by a superadmin, or by a member of the organization that owns the assessment (the creator of the assessment sets the organization ownership). 

In addition, it became apparent in integration tests that failing to update a signed in user's session was a significant security hole. If an admin removes a person from the organization, they could still operate as a member of that organization until their session expired, which really does not seem right. Expecting the admin to delete their session is depending too much on user behavior to ensure security. So I am editing the session for the user if they have one. This is something that we may wish to do elsewhere.

2020-06-30 00:14 UTC, DwayneJengSage requested changes

2020-06-30 00:14 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/AuthUtils.java
> +        }
What does it mean if an assessment has no owner ID? Is that a caller error or a server error?

If not having an owner ID is possible and not an error, should superadmins have access to assessments without owners?

Similarly for checkSharedAssessmentOwnership()

2020-06-30 00:14 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/AuthUtils.java
> +        }
If these can happen in tests, should superadmins have access to these?

2020-06-30 21:16 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/AuthUtils.java
> +        }
It should always have an ownerId, so this would be a server error. Removed and replaced with a checkNotNull().

2020-06-30 21:18 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/AuthUtils.java
> +        }
Good point. Changed this so they are always accessible to superadmins.

2020-07-06 21:54 UTC, DwayneJengSage approved these changes

2020-07-06 22:23 UTC, merged