SubpopulationController, SubstudyController, SurveyController
Sage-Bionetworks/BridgeServer2 pull request #25
Opened 2019-05-15 22:00 UTC by alxdarksage

2019-05-15 23:41 UTC, DwayneJengSage requested changes

2019-05-15 23:41 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/SurveyControllerTest.java
> +    public void physicalDeleteAllowedForAdmin() throws Exception {
Minor: Test annotation.

2019-05-15 23:41 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/SurveyControllerTest.java
> +
Missing test publishSurveyInvalidatesCache()?

2019-05-16 21:02 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/SurveyControllerTest.java
> +    public void physicalDeleteAllowedForAdmin() throws Exception {
Added

2019-05-16 21:04 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/SurveyControllerTest.java
> +
Yes, restored with a boolean third argument.

2019-05-16 21:31 UTC, DwayneJengSage approved these changes

2019-05-16 22:29 UTC, merged