Enrollment note
Sage-Bionetworks/BridgeServer2 pull request #448
Opened 2021-10-11 18:06 UTC by jnelsonjava

For BRIDGE-3095 (draft)

- Add note field to enrollment records for a study-scoped participant note.
- Create route to update existing enrollments

2021-10-18 22:14 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/models/studies/Enrollment.java
> +     *
Focus on the security constraints or who can read/write.

2021-10-18 22:16 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
> +import static org.sagebionetworks.bridge.AuthUtils.IS_ONLY_DEVELOPER;
IS_ONLY_DEVELOPER is not used anymore.

2021-10-18 22:36 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
in updateEnrollment, allow the note to be set unless "self". Otherwise it should carry over from previous enrollment.

2021-10-18 22:37 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +    // TODO: recomment in this test
Figure out why this was failing.

2021-10-18 22:44 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +        assertNull(otherEnrollment.getNote());
Retrieve the actual enrollments from the account to test this.

2021-10-18 22:46 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/EnrollmentControllerTest.java
> +        // TODO: should this include the updateUserEnrollments route?
No, don't include it.

2021-10-18 22:48 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/spring/controllers/EnrollmentControllerTest.java
> +        doReturn(session).when(controller).getAdministrativeSession();
Need to set roles in the RequestContext to trigger the AuthUtils.

2021-10-26 20:05 UTC, alxdarksage requested changes
Very close to done. Maybe a rename and one question about logic if an enrollment record is changed, will it have the side effect of potentially nullifying any note that is present?

2021-10-26 20:05 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
> +            newEnrollment.setNote(null);
If the user later withdrew themselves, would this null out the note? If you're concerned about a user setting this field, maybe it needs to be nullified somewhere that clearly only applies to self-enrollment.

2021-10-26 20:05 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
> +    public void editEnrollment(Enrollment enrollment) {
It's kind of a drag that the private method is "updateEnrollment" and the public method is "editEnrollment" as elsewhere, we probably call the public method the "update" method. We could swap these.

2021-10-26 20:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +
Can you set your editor to not change these?

2021-10-26 20:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +    }
You only need to test the enrollment you have edited, not all of them.

2021-10-27 00:06 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +
I think I found the right setting. Should be fixed in the future.

2021-10-27 00:10 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
> +            newEnrollment.setNote(null);
Pulled the note setting out of the conditional.

2021-10-27 00:11 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
> +    public void editEnrollment(Enrollment enrollment) {
Went ahead and swapped the names.

2021-10-27 00:13 UTC, jnelsonjava commented on src/main/java/org/sagebionetworks/bridge/services/EnrollmentService.java
Changed this to accept the update regardless of "self" since the caller is an administrator.

2021-10-27 00:17 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +        assertNull(otherEnrollment.getNote());
done

2021-10-27 00:18 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/services/EnrollmentServiceTest.java
> +    }
Paired it down to find the appropriate enrollment.

2021-10-27 17:26 UTC, alxdarksage approved these changes

2021-10-27 20:09 UTC, merged