Adds rate limiting for participant file downloads
Sage-Bionetworks/BridgeServer2 pull request #606
Opened 2022-07-05 23:39 UTC by imranmaj

[https://sagebionetworks.jira.com/browse/BRIDGE-2941](https://sagebionetworks.jira.com/browse/BRIDGE-2941)

Rate limits by bytes

2022-07-06 00:02 UTC, zaro0508 commented on src/main/java/org/sagebionetworks/bridge/BridgeConstants.java
> +    public static final long PARTICIPANT_FILE_RATE_LIMITER_REFILL_BYTES_TEST = 1_000; // 1 MB
shouldn't this be `1KB`?

2022-07-06 00:02 UTC, zaro0508 commented on src/main/java/org/sagebionetworks/bridge/BridgeConstants.java
> +    public static final long PARTICIPANT_FILE_RATE_LIMITER_INITIAL_BYTES_PROD = 1_000_000; // 1 MB
whaoo! you can assign `1_000_000` as a `long` type?

2022-07-06 16:21 UTC, imranmaj commented on src/main/java/org/sagebionetworks/bridge/BridgeConstants.java
> +    public static final long PARTICIPANT_FILE_RATE_LIMITER_REFILL_BYTES_TEST = 1_000; // 1 MB
Yes thanks

2022-07-06 16:23 UTC, imranmaj commented on src/main/java/org/sagebionetworks/bridge/BridgeConstants.java
> +    public static final long PARTICIPANT_FILE_RATE_LIMITER_INITIAL_BYTES_PROD = 1_000_000; // 1 MB
Yeah it's nice for readability!

2022-07-06 18:06 UTC, imranmaj commented on src/main/java/org/sagebionetworks/bridge/util/ByteRateLimiter.java
> +    private long maximumTokens;
maximumBytes

2022-07-06 22:14 UTC, jnelsonjava approved these changes
Looks good!

2022-07-13 21:09 UTC, imranmaj commented on src/main/java/org/sagebionetworks/bridge/services/ParticipantFileService.java
> +        isProduction = config.isProduction();
Place in BridgeServer2.conf

2022-07-14 04:55 UTC, DwayneJengSage requested changes
Overall looks good. A few minor comments.

2022-07-14 04:55 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/BridgeConstants.java
> +    public static final long PARTICIPANT_FILE_RATE_LIMITER_REFILL_BYTES_TEST = 1_000; // 1 KB
You can replace these with config entries in BridgeServer2.conf. See for example https://github.com/Sage-Bionetworks/BridgeServer2/blob/develop/src/main/resources/BridgeServer2.conf#L20

2022-07-14 04:55 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/ParticipantFileService.java
> +            }
Add unit test case for when getObjectMetadata throws a 404 and another test case for when it throws a different exception (such as 500 Internal Server Error).

2022-07-14 04:55 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/ParticipantFileService.java
> +        }
Add unit test case for when getParticipantFiles returns null.

2022-07-14 04:55 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/services/ParticipantFileServiceTest.java
> +        });
Minor: You can use thenReturn() instead of thenAnswer() to simply return a previously created ForwardCursorPagedResourceList. This way, you won't need to create a lambda, and the code will be simpler and easier to read.

2022-07-14 04:55 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/util/ByteRateLimiter.java
> +    private long refillAmount;
I recommend marking the immutable fields as final (eg `private final long maximumBytes`). This tells the compiler that this field can never be change, so someone editing this class in the future won't accidentally try to change the value.

2022-07-14 22:05 UTC, DwayneJengSage requested changes

2022-07-14 22:05 UTC, DwayneJengSage commented on src/main/resources/BridgeServer2.conf
> +participant-file.rate-limiter.test.refill-bytes = 1000
You can instead use participant-file.rate-limiter.initial-bytes and prod.participant-file.rate-limiter.initial-bytes. All stages will automatically pick up the base entry, and prod will automatically pick up the prod value. You don't need a hard-coded switch on isProduction.

2022-07-15 16:27 UTC, imranmaj commented on src/main/resources/BridgeServer2.conf
> +participant-file.rate-limiter.test.refill-bytes = 1000
Ah I see, thanks, that's cool

2022-07-15 21:37 UTC, DwayneJengSage approved these changes

2022-07-16 00:00 UTC, merged