Add demographics validation
Sage-Bionetworks/BridgeServer2 pull request #633
Opened 2022-10-25 19:37 UTC by imranmaj

https://sagebionetworks.jira.com/browse/BRIDGE-3030 and https://sagebionetworks.jira.com/browse/BRIDGE-3352

2022-12-07 22:19 UTC, imranmaj commented on src/test/java/org/sagebionetworks/bridge/json/DemographicUserSerializerDeserializerTest.java
> +        values.add(new DemographicValue((String) null));
Remove

2022-12-07 22:21 UTC, imranmaj commented on src/test/java/org/sagebionetworks/bridge/json/DemographicValueDeserializerTest.java
> +    public void decimalPosLarge() throws JsonMappingException, JsonProcessingException {
Wrong name

2022-12-07 22:27 UTC, imranmaj commented on src/test/java/org/sagebionetworks/bridge/services/DemographicServiceTest.java
> +        // nothing else should happen because the app config element key does nkot match
Typo

2022-12-08 10:31 UTC, DwayneJengSage requested changes
In addition, changes to move DemographicsValidationConfig to its own storage and APIs, and enabling validation for all demographics, app-level and study-level.

2022-12-08 10:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/models/studies/DemographicValuesValidationConfigurationTest.java
> +    public void serialize() throws JsonProcessingException {
Do we have a test where we deserialize a valid validation config?

2022-12-08 10:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/services/DemographicServiceTest.java
> +        verify(appConfigElementService).getMostRecentElements(TEST_APP_ID, false);
We should also verify that the saved demographics have no invalidity.

2022-12-08 10:31 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/validators/DemographicValuesValidator.java
> +    private static final String INVALID_CONFIGURATION_MIN_LARGER_THAN_MAX = INVALID_CONFIGURATION;
Mentioned in code review that we shouldn't hide invalid configuration. If we're moving this to its own API, we can use the same Validator pattern we use for other APIs and ensure that our configuration as always valid.

2022-12-16 12:16 UTC, DwayneJengSage requested changes
Looks good. Just comments about permissions.

2022-12-16 12:16 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/spring/controllers/DemographicController.java
> +            session = getAuthenticatedSession(Roles.RESEARCHER, Roles.STUDY_COORDINATOR);
Should add `CAN_UPDATE_STUDIES.checkAndThrow(STUDY_ID, studyId);` See StudyController.updateStudy() for an example.

Also, this should be DEVELOPER and STUDY_DESIGNER, not RESEARCHER and STUDY_COORDINATOR.

2022-12-16 12:16 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/spring/controllers/DemographicController.java
> +            session = getAuthenticatedSession(Roles.RESEARCHER, Roles.STUDY_COORDINATOR);
Similar, this should use `CAN_READ_STUDIES.checkAndThrow(STUDY_ID, studyId);` See StudyController.getStudy() for example.

We can make this available to RESEARCHER, DEVELOPER, STUDY_COORDINATOR, and STUDY_DESIGNER.

2022-12-16 12:16 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/spring/controllers/DemographicController.java
> +            session = getAuthenticatedSession(Roles.RESEARCHER, Roles.STUDY_COORDINATOR);
This should have the same CAN_UPDATE_STUDIES check and permissions as saveValidationConfig().

2022-12-16 12:16 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/spring/controllers/DemographicController.java
> +            session = getAuthenticatedSession(Roles.ADMIN);
App-wide permissions should be DEVELOPER. This applies to all 3 of the APIs.

2023-01-10 01:39 UTC, DwayneJengSage approved these changes

2023-01-11 22:03 UTC, merged