Some final changes before adding migration code
Sage-Bionetworks/BridgeServer2 pull request #78
Opened 2019-08-02 20:32 UTC by alxdarksage

- Changed TemplateService's `getTemplateForUser` to `getTemplateRevisionForUser` because we actually want the revision, not the template;
- Added the TemplateMigrationService which can be called on update idempotently to move over the study templates to the enhanced templates system.
- On a physical delete of a study, physical delete all the templates (this in turn removes all the revisions).

2019-08-02 22:24 UTC, DwayneJengSage requested changes

2019-08-02 22:24 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/services/StudyServiceMockTest.java
> +
We should verify calls to deleteTemplatePermanently().

2019-08-02 22:24 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/StudyService.java
> +            } while(!page.getItems().isEmpty());
How do indices in SQL work? Would it be better to create a getTemplatesForStudy() API instead of making a bunch of micro-calls for each template type?

2019-08-02 22:24 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/StudyService.java
> +            } while(!page.getItems().isEmpty());
We should also consider adding a maximum here, in case a bug somewhere causes this code to go into an infinite loop.

2019-08-12 16:43 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/services/StudyService.java
> +            } while(!page.getItems().isEmpty());
Added a method to specifically do this delete... there's no reason the DAO can't do this.

2019-08-12 16:43 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/services/StudyServiceMockTest.java
> +
Added

2019-08-12 20:05 UTC, DwayneJengSage approved these changes

2019-08-12 20:17 UTC, merged