Selectable by criteria
Sage-Bionetworks/BridgeServer2 pull request #88
Opened 2019-08-19 17:21 UTC by alxdarksage

BRIDGE-2542: we currently select the first language a user provides as an acceptable alternative, rather than looking to see if we have the best fit language for the user. Fixed here with some new utility methods that take the entire set of Criteria-filterable objects and sorting all matches by language weight.

TODO: Need to verify that when criteria don't declare a language, the sort order is not changed (for backwards compatibility and also because that would make it impossible to tell what is selected just by looking at a list of the possibilities).

2019-08-19 17:23 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/services/AppConfigService.java
> +        matches.sort(Comparator.comparingLong(AppConfig::getCreatedOn));
So are we returning the most recent match and *not* sorting by language here? It seems we need to support language sorting here too.

2019-08-19 23:01 UTC, DwayneJengSage requested changes

2019-08-19 23:01 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/models/CriteriaUtils.java
> +        }
Do we have a unit test for sorting by a secondary comparator?

2019-08-20 21:51 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/models/CriteriaUtils.java
> +        }
Added test.

2019-08-20 23:55 UTC, DwayneJengSage approved these changes

2019-08-21 17:43 UTC, merged